# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HealthPad Companion' do
pod "AsyncSwift"
pod "ActionKit"
pod "SwiftString"
pod "Charts"
pod "GradientView"
end
